# applicant
name = "Chris Reynolds"
year = "1998"
flavor = "Hubble"
institution_phd = "University of Cambridge"
institution_host = "University of Colorado, Boulder"

# application
title = "The Central Engines and Immediate Environments of Active Galactic Nuclei"
science_category = "Compact Objects and Accretion"
abstract = nan
url = "TBD new upload"
