# applicant
name = "Martin Bureau"
year = "2001"
flavor = "Hubble"
institution_phd = "Australian National University"
institution_host = "Columbia University"

# application
title = "Galactic Dynamics Over 4 Orders of Magnitude in Radii"
science_category = "Galaxies and the Intergalactic Medium"
abstract = '''
As a Hubble Fellow, I will combine observational, theoretical, and archival work to study the connection between the nuclear properties of galaxies and their global structure and dynamics. For this, I will use three different but complementary approaches, each involving data obtained through vastly different means over 4 orders of magnitude in radii. First, I will carry out archival work to extend our knowledge of correlations between the nuclear properties of galaxies and their large scale shape and dynamics. Second, I will model the kinematics of a few carefully chosen early-type galaxies over a large range of scales, to identify the dynamical mechanisms connecting the interior parts to the exterior. Last, I will initiate an observational project to directly test proposed bar-driven secular evolution scenarios for the bulges of spirals. All three projects rely heavily on data from both HST and the unique panoramic integral-field spectrograph SAURON.
'''
url = "https://drive.google.com/file/d/14JCOnUGCkW4ZO0yPQcyy6w7AhP8CM0Ph"
