# applicant
name = "Keivan Stassun"
year = "2001"
flavor = "Hubble"
institution_phd = "University of Wisconsin–Madison"
institution_host = "University of Wisconsin–Madison"

# application
title = "Observational Tests of Pre-Main-Sequence Stellar Evolution Theory"
science_category = "Stellar Physics"
abstract = nan
url = "https://drive.google.com/file/d/1x8CN9ABIrHgSRXrijsE_AvgaYEm4HEhZ"
