# applicant
name = "Marla Geha"
year = "2003"
flavor = "Hubble"
institution_phd = "University of California, Santa Cruz"
institution_host = "Carnegie Observatories"

# application
title = "The Nature and Origin of Dwarf Elliptical Galaxies"
science_category = "Galaxies and the Intergalactic Medium"
abstract = nan
url = "TBD new upload"
