# applicant
name = "Jeffrey Newman"
year = "2003"
flavor = "Hubble"
institution_phd = "University of California, Berkeley"
institution_host = "Lawrence Berkeley National Laboratory"

# application
title = nan
science_category = "Galaxies and the Intergalactic Medium"
abstract = nan
url = "https://drive.google.com/file/d/1REkzfxTSFsIYHXccSlZGvi4DvVKnrT_p"
