# applicant
name = "Hiranya Peiris"
year = "2004"
flavor = "Hubble"
institution_phd = "Princeton University"
institution_host = "University of Chicago"

# application
title = "Constraining Fundamental Physics Using the Cosmic Microwave Background and Complementary Data"
science_category = "Physics and Cosmology"
abstract = nan
url = "https://drive.google.com/file/d/1tSw5H5mC2xk7UR2yOUM6HJrFEk6-MhX5"
