# applicant
name = "Sean Brittain"
year = "2004"
flavor = "Michelson"
institution_phd = "TBD look this up"
institution_host = "TBD look this up"

# application
title = nan
science_category = "Exoplanet Formation and Protoplanetary Disks"
abstract = nan
url = "TBD good version"
