# applicant
name = "Sean Brittain"
year = "2004"
flavor = "Michelson"
institution_phd = "University of Notre Dame"
institution_host = "National Radio Astronomy Observatory"

# application
title = nan
science_category = "Exoplanet Formation and Protoplanetary Disks"
abstract = nan
url = "https://drive.google.com/file/d/1QrFxUfK0FWH1IV3DjENc6i_avzdkm4zj"
