# applicant
name = "Mark Krumholz"
year = "2005"
flavor = "Hubble"
institution_phd = "University of California, Berkeley"
institution_host = "Princeton University"

# application
title = "Star Formation Efficiency and the Life Cycle of Molecular Clouds"
science_category = "Stellar Physics"
abstract = nan
url = "https://drive.google.com/file/d/1uBvafigUDpqwqkCKC0kuWxbl6z48GKEa"
