# applicant
name = "Kelle Cruz"
year = "2007"
flavor = "Spitzer"
institution_phd = "TBD look up"
institution_host = "TBD look up"

# application
title = "Nearby, Young Brown Dwarfs: A Comprehensive Study"
science_category = "Stellar Physics"
abstract = nan
url = "TBD new upload"
