# applicant
name = "Kristian Finlator"
year = "2009"
flavor = "Hubble"
institution_phd = "University of Arizona"
institution_host = "University of California, Santa Barbara"

# application
title = "Radiative Hydrodynamic Simulations of Galaxies in the Reionization Epoch"
science_category = "Galaxies and the Intergalactic Medium"
abstract = nan
url = "TBD new upload"
