# applicant
name = "Shelley Wright"
year = "2009"
flavor = "Hubble"
institution_phd = "University of California, Los Angeles"
institution_host = "University of California, Berkeley"

# application
title = "Galactic Disk Formation, AGN, and Metallicity in the Early Universe: Spatially Resolved Spectroscopy of High-Redshift Galaxies"
science_category = "Galaxies and the Intergalactic Medium"
abstract = nan
url = "https://drive.google.com/file/d/1QiHvjYDGBTSUIRGD93tcTx1B25dj4UV1"
