# applicant
name = "Tabetha Boyajian"
year = "2009"
flavor = "Hubble"
institution_phd = "Georgia State University"
institution_host = "Georgia State University"

# application
title = "The Angular Diameters and Physical Properties of Low-Mass Stars"
science_category = "Stellar Physics"
abstract = nan
url = "TBD good version"
