# applicant
name = "Emily Rauscher"
year = "2010"
flavor = "Sagan"
institution_phd = "Columbia University"
institution_host = "University of Arizona"

# application
title = nan
science_category = "Exoplanets and Habitability"
abstract = nan
url = "https://drive.google.com/file/d/1tKJ5LYgYUsZocxVqRkqJBkkmNnqPYddq"
