# applicant
name = "Nicolas Yunes"
year = "2010"
flavor = "Einstein"
institution_phd = "Pennsylvania State University"
institution_host = "Massachusetts Institute of Technology"

# application
title = "Exploiting Gravitational Wave Observations: Modeling of Extreme-Mass Ratio Inspirals and Tests of Fundamental Physics"
science_category = "Physics and Cosmology"
abstract = nan
url = "https://drive.google.com/file/d/1BnlQto6RYos6ZgqtU5ku3ORZWVY2Jc6C"
