# applicant
name = "Tony Mroczkowski"
year = "2010"
flavor = "Einstein"
institution_phd = "TBD look up"
institution_host = "TBD look up"

# application
title = "Revealing Cluster Astrophysics and Evolution with MUSTANG"
science_category = "Galaxies and the Intergalactic Medium"
abstract = nan
url = "TBD new upload"
