# applicant
name = "Daniel Fabrycky"
year = "2010"
flavor = "Hubble"
institution_phd = "TBD look up"
institution_host = "TBD look up"

# application
title = "Dynamical Architecture of Planetary Systems"
science_category = "Exoplanets and Habitability"
abstract = nan
url = "TBD new upload"
