# applicant
name = "Nicolas Yunes"
year = "2010"
flavor = "Einstein"
institution_phd = "TBD look up"
institution_host = "TBD look up"

# application
title = "Exploiting Gravitational Wave Observations: Modeling of Extreme-Mass Ratio Inspirals and Tests of Fundamental Physics"
science_category = "Physics and Cosmology"
abstract = nan
url = "TBD good version"
