# applicant
name = "Emily Rauscher"
year = "2010"
flavor = "Sagan"
institution_phd = "Columbia University"
institution_host = "TBD look up"

# application
title = nan
science_category = "Exoplanets and Habitability"
abstract = nan
url = "TBD new upload"
