# applicant
name = "Daniel Fabrycky"
year = "2010"
flavor = "Hubble"
institution_phd = "Princeton University"
institution_host = "University of California, Santa Cruz"

# application
title = "Dynamical Architecture of Planetary Systems"
science_category = "Exoplanets and Habitability"
abstract = nan
url = "https://drive.google.com/file/d/1wXS9TyAJaQmGHvXqcTp8S9-vVjj374E5"
