# applicant
name = "Steven Finkelstein"
year = "2011"
flavor = "Hubble"
institution_phd = "Arizona State University"
institution_host = "University of Texas at Austin"

# application
title = "Measuring the Evolution of Galaxy Physical Properties from z = 2 – 8"
science_category = "Galaxies and the Intergalactic Medium"
abstract = nan
url = "https://drive.google.com/file/d/1AI0TikfSTi16nCZwpYuQczCV750_DVcQ"
