# applicant
name = "Ken Shen"
year = "2011"
flavor = "Einstein"
institution_phd = "TBD look up"
institution_host = "TBD look up"

# application
title = "Theoretical Investigations of Type Ia Supernova Progenitors"
science_category = "Compact Objects and Accretion"
abstract = nan
url = "TBD good version"
