# applicant
name = "David Kipping"
year = "2011"
flavor = "Sagan"
institution_phd = "University College London"
institution_host = "Harvard University"

# application
title = "A Search for Exomoons"
science_category = "Exoplanets and Habitability"
abstract = nan
url = "https://drive.google.com/file/d/16UsT5m5sxqUHtB7uHjqz0KMHIJct8S1g"
