# applicant
name = "Ken Shen"
year = "2011"
flavor = "Einstein"
institution_phd = "University of California, Santa Barbara"
institution_host = "Lawrence Berkeley National Laboratory"

# application
title = "Theoretical Investigations of Type Ia Supernova Progenitors"
science_category = "Compact Objects and Accretion"
abstract = nan
url = "https://drive.google.com/file/d/1Jrc_Qlb_oPkkptVq-064bB8b_R5A3EsM"
