# applicant
name = "Julie Hlavacek-Larrondo"
year = "2012"
flavor = "Einstein"
institution_phd = "University of Cambridge"
institution_host = "TBD look up"

# application
title = "Unravelling AGN feedback: from isolated elliptical galaxies to massive clusters of galaxies"
science_category = "Galaxies and the Intergalactic Medium"
abstract = nan
url = "TBD good version"
