# applicant
name = "Ann-Marie Madigan"
year = "2012"
flavor = "Einstein"
institution_phd = "Columbia University"
institution_host = "TBD look up"

# application
title = "The dynamics of stars in disks around massive black holes"
science_category = "Stellar Physics"
abstract = nan
url = "TBD good version"
