# applicant
name = "Krzysztof Nalewajko"
year = "2013"
flavor = "Einstein"
institution_phd = "Nicolaus Copernicus Astronomical Center"
institution_host = "University of Colorado Boulder"

# application
title = "Understanding Gamma-Ray Flares of Blazars"
science_category = "Compact Objects and Accretion"
abstract = nan
url = "https://drive.google.com/file/d/1CMafAR3aqvhk-a-gcIj-pSfccS-nfGMW"
