# applicant
name = "Grant Tremblay"
year = "2014"
flavor = "Einstein"
institution_phd = "Rochester Institute of Technology"
institution_host = "TBD look up"

# application
title = "Unifying Chandra with ALMA: Star Formation amid Kinematic Black Hole Feedback"
science_category = "Compact Objects and Accretion"
abstract = nan
url = "TBD good version"
