# applicant
name = "Francois Foucart"
year = "2014"
flavor = "Einstein"
institution_phd = "Cornell University"
institution_host = "Lawrence Berkeley National Laboratory"

# application
title = "Simulating compact binary mergers for multi-messenger astronomy"
science_category = "Gravitational Wave Astrophysics"
abstract = nan
url = "https://drive.google.com/file/d/1PCyva3eoYnnruvbaz3oChgW5iKK-SPxH"
