# applicant
name = "Grant Tremblay"
year = "2014"
flavor = "Einstein"
institution_phd = "Rochester Institute of Technology"
institution_host = "Yale University"

# application
title = "Unifying Chandra with ALMA: Star Formation amid Kinematic Black Hole Feedback"
science_category = "Compact Objects and Accretion"
abstract = nan
url = "https://drive.google.com/file/d/1iEiuT5T2pJUCSbnL81C8xgxdYRa69Piq"
