# applicant
name = "Brooke Simmons"
year = "2015"
flavor = "Einstein"
institution_phd = "TBD look up"
institution_host = "TBD look up"

# application
title = "Illuminating the Black Hole-Galaxy Connection"
science_category = "Galaxies and the Intergalactic Medium"
abstract = nan
url = "TBD new upload"
