# applicant
name = "Daniel Foreman-Mackey"
year = "2015"
flavor = "Sagan"
institution_phd = "New York University"
institution_host = "University of Washington"

# application
title = nan
science_category = "Exoplanets and Habitability"
abstract = nan
url = "https://drive.google.com/file/d/1bxmVmvv0a8HahzUeXKFI1hiWiaspnDyr"
