# applicant
name = "Adrian Liu"
year = "2015"
flavor = "Hubble"
institution_phd = "Massachusetts Institute of Technology"
institution_host = "University of California, Berkeley"

# application
title = "From a Detection to Astrophysics in 21 cm Cosmology"
science_category = "Physics and Cosmology"
abstract = nan
url = "https://drive.google.com/file/d/1Kuff9sluM2t5PHVXy6pbPGzl54gHrfXO"
