# applicant
name = "Tyler Robinson"
year = "2015"
flavor = "Sagan"
institution_phd = "TBD look up"
institution_host = "TBD look up"

# application
title = "Bridging the Theory Gap: Developing a Novel Cloud Model for Exoplanets"
science_category = "Exoplanets and Habitability"
abstract = nan
url = "TBD good version"
