# applicant
name = "Daniel Foreman-Mackey"
year = "2015"
flavor = "Sagan"
institution_phd = "TBD look up"
institution_host = "TBD look up"

# application
title = nan
science_category = "Exoplanets and Habitability"
abstract = nan
url = "TBD good version"
