# applicant
name = "Tyler Robinson"
year = "2015"
flavor = "Sagan"
institution_phd = "University of Washington"
institution_host = "University of California, Santa Cruz"

# application
title = "Bridging the Theory Gap: Developing a Novel Cloud Model for Exoplanets"
science_category = "Exoplanets and Habitability"
abstract = nan
url = "https://drive.google.com/file/d/1SZXw7_ZVWqNAcVEN19sq6uxlU-zIFq0h"
