# applicant
name = "Peter Behroozi"
year = "2015"
flavor = "Hubble"
institution_phd = "Stanford University"
institution_host = "University of California, Berkeley"

# application
title = "Uncovering Connections between Galaxy and Dark Matter Halo Assembly Histories"
science_category = "Galaxies and the Intergalactic Medium"
abstract = nan
url = "https://drive.google.com/file/d/1rksTYMcfgWf-qqUNRE7h3rLaVE0jgnz-"
