# applicant
name = "Lia Corrales"
year = "2016"
flavor = "Einstein"
institution_phd = "Columbia University"
institution_host = "University of Wisconsin–Madison"

# application
title = "Bringing the Galactic Center into focus with dust scattering"
science_category = "The Milky Way and Resolved Stellar Populations"
abstract = nan
url = "https://drive.google.com/file/d/10pmYYRgQKd-p8FoCZ193WKD2GJufPk2g"
