# applicant
name = "Sean Johnson"
year = "2016"
flavor = "Hubble"
institution_phd = "University of Chicago"
institution_host = "Princeton University"

# application
title = "Unveiling the relationship between AGN and the CGM: feeding and feedback"
science_category = "Galaxies and the Intergalactic Medium"
abstract = '''
As a Hubble Fellow at Yale, I will combine the resources of both Palomar and Keck to conduct the first large and comprehensive survey of the Circum-Galactic Medium (CGM) of Active Galactic Nuclei (AGN) to gain insight into AGN feeding and feedback. The survey will begin with the construction of a large sample of obscured AGN with CGM constraints enabling a detailed comparison between the CGM of AGN hosts and a carefully matched control sample of non-AGN galaxies. I will then search for connections between AGN outflows and the CGM through a combination of high resolution spectroscopy constraining the ionization state of the absorbing gas and deep, spatially resolved spectra to reveal the presence of extended AGN-driven outflows. This unique survey will use my own experience with the CGM and the sensitivity of absorption spectroscopy to unveil the relationship between AGN feeding/feedback and the CGM and provide new insights into both black hole growth and galaxy evolution to address two of the five key questions of the Cosmic Origins Program.
'''
url = "https://drive.google.com/file/d/14Xe8qsSMcrD-BGgVVzdwrpflZoijlAUg"
