# applicant
name = "Diana Dragomir"
year = "2016"
flavor = "Hubble"
institution_phd = "University of British Columbia"
institution_host = "Massachusetts Institute of Technology"

# application
title = "Characterizing Small Planets Around Bright Stars"
science_category = "Exoplanets and Habitability"
abstract = nan
url = "https://drive.google.com/file/d/1WM4-jxqc9xHUyr5JHqRnqIIJGv3VpmiP"
