# applicant
name = "Lia Corrales"
year = "2016"
flavor = "Einstein"
institution_phd = "TODO look up"
institution_host = "TODO look up"

# application
title = "Bringing the Galactic Center into focus with dust scattering"
science_category = "The Milky Way and Resolved Stellar Populations"
abstract = nan
url = "TODO good version"
