# applicant
name = "Siyao Xu"
year = "2017"
flavor = "Hubble"
institution_phd = "Peking University"
institution_host = "University of Wisconsin—Madison"

# application
title = "The Role of Neutral-­‐ion Coupling in Star Formation"
science_category = "Physics and Cosmology"
abstract = nan
url = "TODO good version"
