# applicant
name = "Raphaelle Haywood"
year = "2017"
flavor = "Sagan"
institution_phd = "University of St Andrews"
institution_host = "Harvard University"

# application
title = "Breaking the Ultimate Barrier to Characterizing Other Earths"
science_category = "Exoplanets and Habitability"
abstract = '''
The TESS mission will discover 500 Earths and super-Earths orbiting the closest stars. These will be ideal candidates to determine their
compositions, characterize their atmospheres, assess their habitability. However, these opportunities will not be realized unless we can
determine their most fundamental parameter: mass. This is precluded by the magnetic activity of the host star. I will identify the physical
processes at play using exquisite HARPS-N observations of the Sun, and examine the magnetic behaviour of other stars. Leveraging on
these lessons, I will develop recipes for precise mass determinations, to enable the full characterization of small planets.
'''
url = "https://drive.google.com/file/d/1HuZ9owZD_sX2wMFalgeDGYZ43ZcsAMBO"
