# applicant
name = "Johanna Teske"
year = "2017"
flavor = "Hubble"
institution_phd = "University of Arizona"
institution_host = "Carnegie Institution"

# application
title = "Characterizing the Diversity of Small Planet Compositions via Planet Densities and Host Star Abundances"
science_category = "Exoplanets and Habitability"
abstract = nan
url = "https://drive.google.com/file/d/1WUxSDLP-mhOUfEnQa_xG3RN3N-sT8DV_"
