# applicant
name = "Brett McGuire"
year = "2017"
flavor = "Hubble"
institution_phd = "California Institute of Technology"
institution_host = "National Radio Astronomy Observatory"

# application
title = "Getting Away from One-Pot Syntheses: Heterogeneity in Molecular Evolution Revealed with ALMA"
science_category = "The Milky Way and Resolved Stellar Populations"
abstract = nan
url = "https://drive.google.com/file/d/17TvwAAIp9WL5MZ8u8ktWjMNkHznUZFj-"
