# applicant
name = "Benedikt Diemer"
year = "2018"
flavor = "Einstein"
institution_phd = "University of Chicago"
institution_host = "Harvard University"

# application
title = "Mapping the true boundary of dark matter halos with the splashback radius"
science_category = "Galaxies and the Intergalactic Medium"
abstract = nan
url = "https://drive.google.com/file/d/1U8oSXx2H0kT4Z1kLyJlb0R7ZxQXPZDi4"
