# applicant
name = "Benedikt Diemer"
year = "2018"
flavor = "Einstein"
institution_phd = "TODO look up"
institution_host = "TODO look up"

# application
title = "Mapping the true boundary of dark matter halos with the splashback radius"
science_category = "Galaxies and the Intergalactic Medium"
abstract = nan
url = "TODO new upload"
