# applicant
name = "Christopher Theissen"
year = "2019"
flavor = "Sagan"
institution_phd = "TODO look up"
institution_host = "TODO look up"

# application
title = "Planetary Collisions around Low-Mass Stars: Constraining the Timescale for Collisions and Testing the Origin of the Kepler Dichotomy"
science_category = "Exoplanets and Habitability"
abstract = nan
url = "TODO new upload"
