# applicant
name = "Georgia Panopoulou"
year = "2019"
flavor = "Hubble"
institution_phd = "University of Crete"
institution_host = "California Institute of Technology"

# application
title = "A unique approach to the determination of the Galactic magnetic field using starlight and synchrotron polarization observations"
science_category = "The Milky Way and Resolved Stellar Populations"
abstract = nan
url = "https://drive.google.com/file/d/1egOEudfDEbzAxJ-ay_ZsHcS9z7FbNPRU"
