# applicant
name = "Dillon Brout"
year = "2019"
flavor = "Einstein"
institution_phd = "University of Pennsylvania"
institution_host = "Harvard University"

# application
title = "Improving Cosmological Constraints with the Dark Energy Survey Supernova Program and a Decade of Type Ia Supernovae"
science_category = "Physics and Cosmology"
abstract = nan
url = "https://drive.google.com/file/d/1BEYxHYRcymzYtqTHPFbsx_3ISMoydbD-"
