# applicant
name = "Dillon Brout"
year = "2019"
flavor = "Einstein"
institution_phd = "TODO look up"
institution_host = "TODO look up"

# application
title = "Improving Cosmological Constraints with the Dark Energy Survey Supernova Program and a Decade of Type Ia Supernovae"
science_category = "Physics and Cosmology"
abstract = nan
url = "TODO good version"
