# applicant
name = "Christopher Theissen"
year = "2019"
flavor = "Sagan"
institution_phd = "Boston University"
institution_host = "University of California, San Diego"

# application
title = "Planetary Collisions around Low-Mass Stars: Constraining the Timescale for Collisions and Testing the Origin of the Kepler Dichotomy"
science_category = "Exoplanets and Habitability"
abstract = nan
url = "https://drive.google.com/file/d/1HZK1Z_Jst2jYnsMp5jCMqJ-OiqwRPqVF"
