# applicant
name = "Michael Zevin"
year = "2020"
flavor = "Hubble"
institution_phd = "Northwestern University"
institution_host = "University of Chicago"

# application
title = "Deciphering the Biography of Massive Stars: Compact Object Mergers as a Rosetta Stone"
science_category = "Gravitational Wave Astrophysics"
abstract = nan
url = "https://drive.google.com/file/d/1wNNuztYR_ai5swfw_8Yuf19YrPo5oHhY"
