# applicant
name = "Siyao Xu"
year = "2020"
flavor = "Hubble"
institution_phd = "Peking University"
institution_host = "TODO look up"

# application
title = "Cosmic Ray Diffusion in the Multi-phase Interstellar Medium"
science_category = "Physics and Cosmology"
abstract = nan
url = "TBD good version"
