# applicant
name = "Sarah Millholland"
year = "2020"
flavor = "Sagan"
institution_phd = "Yale University"
institution_host = "Princeton University"

# application
title = "Formation and Dynamics of Short-Period Exoplanetary Systems"
science_category = "Exoplanet Formation and Protoplanetary Disks"
abstract = nan
url = "https://drive.google.com/file/d/1yAzT-mOl4NglPmNLqMMBYPaOvCVN2BDl"
