# applicant
name = "Michael Zevin"
year = "2020"
flavor = "Hubble"
institution_phd = "TODO look up"
institution_host = "TODO look up"

# application
title = "Deciphering the Biography of Massive Stars: Compact Object Mergers as a Rosetta Stone"
science_category = "Compact Objects"
abstract = nan
url = "TODO new upload"
