# applicant
name = "Michael Grudić"
year = "2021"
flavor = "Hubble"
institution_phd = "California Institute of Technology"
institution_host = "TODO look up"

# application
title = "Star-Formation Physics from Cosmos to Cores"
science_category = "Stellar Physics"
abstract = nan
url = "TODO good version"
