# applicant
name = "Michael Grudić"
year = "2021"
flavor = "Hubble"
institution_phd = "California Institute of Technology"
institution_host = "Carnegie Observatories"

# application
title = "Star-Formation Physics from Cosmos to Cores"
science_category = "Stellar Physics"
abstract = nan
url = "https://drive.google.com/file/d/1MYRomMHc1tNckCbuLEWLwzkcQ9QfUVGW"
