# applicant
name = "Anowar Shajib"
year = "2021"
flavor = "Einstein"
institution_phd = "University of California, Los Angeles"
institution_host = "TODO look up"

# application
title = "Internal Structure of Massive Elliptical Galaxies: The Missing Piece at the Intersection of Astrophysics and Cosmology"
science_category = "Galaxies and the Intergalactic Medium"
abstract = nan
url = "TODO new upload"
