# applicant
name = "Pradip Gatkine"
year = "2021"
flavor = "Hubble"
institution_phd = "University of Maryland College Park"
institution_host = "TODO look up"

# application
title = "Probing the CGM-galaxy connection using Multi-object Spectroscopy and Astrophotonics"
science_category = "Galaxies and the Intergalactic Medium"
abstract = nan
url = "TODO new upload, this is in the wrong folder!"
