# applicant
name = "Sultan Hassan"
year = "2022"
flavor = "Hubble"
institution_phd = "University of the Western Cape"
institution_host = "New York University"

# application
title = "Illuminating the Primeval Universe with Lyman$\\alpha$"
science_category = "Galaxies and the Intergalactic Medium"
abstract = nan
url = "https://drive.google.com/file/d/1smixmBAokVM_EHQjHf70K0_HJ7qaad2K"
