# applicant
name = "Sylvia Biscoveanu"
year = "2023"
flavor = "Einstein"
institution_phd = "Massachusetts Institute of Technology"
institution_host = "Northwestern University"

# application
title = "From black holes to the Big Bang: astrophysics and cosmology with gravitational waves and their electromagnetic counterparts"
science_category = "Gravitational Wave Astrophysics"
abstract = nan
url = "https://drive.google.com/file/d/1KNcxKqXMmxrIUjLMbdBCTcd0bq5X95k4"
