# applicant
name = "Adam Smercina"
year = "2024"
flavor = "Hubble"
institution_phd = "University of Michigan"
institution_host = "Space Telescope Science Institute"

# application
title = "A Portrait of the Triangulum: Advancing a New Frontier of Galaxy Evolution with Resolved Stars"
science_category = "The Milky Way and Resolved Stellar Populations"
abstract = '''
In an exciting new observational paradigm, JWST and HST operate simultaneously, providing access to resolved stellar populations in individual nearby galaxies for transformative galaxy evolution science. The first large galaxy with panchromatic HST+JWST observations across its disk, the Triangulum Galaxy, M33, is among the most important members of the Local Group, and also exists at a mass where the physics driving the evolution of disks and spiral structure in galaxies is poorly understood. As a Hubble Fellow, I will conduct a targeted study of this critical benchmark galaxy, allowing me to simultaneously fill an important gap in our understanding of the Local Group, and advance our understanding of low-mass spiral galaxy evolution. I will capitalize on this richness of existing space observations to: (1) chart the complete history of star formation in M33, including its nuclear star cluster and newly-discovered central bar; (2) create a new legacy 10-filter HST+JWST merged catalog of 10 million stars, which I will use to create high-resolution maps of interstellar dust and populations of dusty AGB stars; and (3) use this merged JWST+HST stellar catalog to establish a blueprint for a new era of studying resolved stellar populations in nearby large galaxies from space.
'''
url = "https://drive.google.com/file/d/1kSwpYi9g6uLBIaj9ns0Z6C_r2KAAN2Kd"
